// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Character struct {
	ID                       pgtype.UUID        `json:"id"`
	UserID                   pgtype.UUID        `json:"user_id"`
	Name                     string             `json:"name"`
	Class                    string             `json:"class"`
	Level                    int32              `json:"level"`
	Race                     string             `json:"race"`
	Background               pgtype.Text        `json:"background"`
	Alignment                pgtype.Text        `json:"alignment"`
	ExperiencePoints         int32              `json:"experience_points"`
	Strength                 int32              `json:"strength"`
	Dexterity                int32              `json:"dexterity"`
	Constitution             int32              `json:"constitution"`
	Intelligence             int32              `json:"intelligence"`
	Wisdom                   int32              `json:"wisdom"`
	Charisma                 int32              `json:"charisma"`
	MaxHitPoints             int32              `json:"max_hit_points"`
	CurrentHitPoints         int32              `json:"current_hit_points"`
	TemporaryHitPoints       int32              `json:"temporary_hit_points"`
	ArmorClass               int32              `json:"armor_class"`
	Speed                    int32              `json:"speed"`
	SavingThrowProficiencies []string           `json:"saving_throw_proficiencies"`
	SkillProficiencies       []string           `json:"skill_proficiencies"`
	Equipment                []byte             `json:"equipment"`
	FeaturesTraits           string             `json:"features_traits"`
	Notes                    string             `json:"notes"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        pgtype.Text        `json:"email"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	PublicKey    pgtype.Text        `json:"public_key"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
